name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build app
      run: make
    - name: Install dependencies
      run: sudo add-apt-repository ppa:neurobin/ppa
      run: sudo apt-get update
      run: sudo apt-get install shc
