name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies 1
      run: sudo add-apt-repository ppa:neurobin/ppa
    - name: Install dependencies 2
      run: sudo apt-get update
    - name: Install dependencies 3
      run: sudo apt-get install shc
    - name: Build app
      run: make
