name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install shc git repo
      run: git clone https://github.com/neurobin/shc
    - name: go into folder
      run: cd shc
    - name: configure
      run: ./configure
    - name: make exec
      run: make
    - name: install exec
      run: sudo make install
    
    - name: Make app
      run: make
